# Generated by Django 3.2.3 on 2021-05-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='priority',
            new_name='Priority',
        ),
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1992-01-10'),
            preserve_default=False,
        ),
    ]
